question_data = [{"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "A bear does NOT defecate during hibernation. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "Rabbits are rodents.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "The Platypus is a mammal.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "A caterpillar has more muscles than humans do.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "Cats have whiskers under their legs.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "You can tell the age of a ladybird by counting the spots on his back.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "Rabbits are carnivores.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "The internet browser Firefox is named after the Red Panda.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
